### ISSUE TITLE
The code not work anymore

### ISSUE THREAD

**Issue by Crono03** [M9k/GreenPass-string-replacement#1]
Hi man, 
i tried this software just to make a meme but it gave me this error:

Traceback (most recent call last):
  File "c:\Users\cirel\OneDrive\Desktop\canzone\GreenPass editor.py", line 35, in b45decode
    buf = [BASE45_DICT[c] for c in s.strip()]
  File "c:\Users\cirel\OneDrive\Desktop\canzone\GreenPass editor.py", line 35, in <listcomp>
    buf = [BASE45_DICT[c] for c in s.strip()]
KeyError: '<'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\cirel\OneDrive\Desktop\canzone\GreenPass editor.py", line 61, in <module>
    decoded = b45decode(strip)
  File "c:\Users\cirel\OneDrive\Desktop\canzone\GreenPass editor.py", line 55, in b45decode
    raise ValueError("Invalid base45 string")
ValueError: Invalid base45 string

**Comment by M9k** [comment]
Hi!
Could you tell me which version of python and on which system you are running it?
Are you using a valid greenpass code, taken from a QR Code?
